<?php
	/**
		* Website switcher template
	*/
?>
<?php if($this->getCurrentWebsiteId()): ?>

<?php 
	$_currentWebsiteId = $this->getCurrentWebsiteId();
	$_currentWebsite = $this->getWebsite($_currentWebsiteId); 
	$_websites = $this->getWebsites();
	$id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '';
	$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager =  $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
	$websites = $storeManager->getWebsites();
?>
<div class="switcher website switcher-website" data-ui-id="website-switcher" id="switcher-website<?php /* @escapeNotVerified */ echo $id?>">
	<strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Website') ?></span></strong>
	<div class="actions dropdown options switcher-options">
		<div class="action toggle switcher-trigger" id="switcher-website-trigger<?php /* @escapeNotVerified */ echo $id?>">
			<strong class="view-<?php echo $block->escapeHtml($_currentWebsite->getCode()) ?>">
				<span style="font-size: 15px;">
				<?= $block->escapeHtml($_currentWebsite->getName()) ?>
				</span>
			</strong>
		</div>
		<?php if(count($_websites)): ?>
		<ul class="dropdown switcher-dropdown"
		data-mage-init='{"dropdownDialog":{
		"appendTo":"#switcher-website<?php /* @escapeNotVerified */ echo $id ?> > .options",
		"triggerTarget":"#switcher-website-trigger<?php /* @escapeNotVerified */ echo $id ?>",
		"closeOnMouseLeave": false,
		"triggerClass":"active",
		"parentClass":"active",
		"buttons":null}}'>
			<?php 
				foreach($websites as $website){
					if ($website->getId() != $block->getCurrentWebsiteId()){
						foreach($website->getStores() as $store){
							$wedsiteId = $website->getId();
							$storeObj = $storeManager->getStore($store);
							$storeId = $storeObj->getId();
							$url = $storeObj->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
						?>
						<li class="view-<?php echo $block->escapeHtml($website->getCode()); ?> switcher-option">
							<a href="<?php echo $block->escapeHtml($website->getCode()); ?>" style="font-size: 15px;">
								<?php echo $block->escapeHtml($website->getName()) ?>
							</a>
						</li>
					<?php } ?>
				<?php } ?>
				<?php }  ?>
			</ul>
			<?php endif; ?>
		</div>
	</div>
<?php endif; ?>

<a href='<?php echo $block->escapeHtml($website->getCode()); ?>'>
     <?php echo $block->escapeHtml($website->getName()) ?>
</a>
